/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_v1_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_v1_sources__source_id__patch"];
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Action */
        post: operations["run_action_v1_runs__run_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_v1_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/queue-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts */
        get: operations["counts_v1_leads_queue_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lead Detail */
        get: operations["lead_detail_v1_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Lead */
        patch: operations["patch_lead_v1_leads__lead_id__patch"];
        trace?: never;
    };
    "/v1/leads/{lead_id}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recheck */
        post: operations["recheck_v1_leads__lead_id__recheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}/reanalyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reanalyze */
        post: operations["reanalyze_v1_leads__lead_id__reanalyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_v1_leads__lead_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Outcome */
        post: operations["add_outcome_v1_leads__lead_id__outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make Draft
         * @description 문의 초안 생성 (규칙 템플릿). 발송하지 않는다.
         */
        post: operations["make_draft_v1_leads__lead_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_v1_settings_patch"];
        trace?: never;
    };
    "/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Import */
        post: operations["create_import_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Export */
        post: operations["create_export_v1_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events Stream */
        get: operations["events_stream_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AISettings */
        AISettings: {
            /** Enabled */
            enabled: boolean;
            /** External Transfer Consent */
            external_transfer_consent: boolean;
            /** Engine Label */
            engine_label: string | null;
            /** Monthly Cost Cap */
            monthly_cost_cap: number | null;
            /** Daily Cost Cap */
            daily_cost_cap: number | null;
            /**
             * Key Configured
             * @description API 키 저장 여부 (값은 절대 반환하지 않음)
             */
            key_configured: boolean;
            /** Provider Available */
            provider_available: boolean;
        };
        /** Activity */
        Activity: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
        };
        /** Analysis */
        Analysis: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "rules_only" | "complete" | "failed" | "stale";
            /** Summary */
            summary: string | null;
            /** Summary Engine */
            summary_engine: ("rules" | "ai") | null;
            /** Fit */
            fit: string[];
            /** Unfit */
            unfit: string[];
            /** Uncertain */
            uncertain: string[];
            /** Deliverables */
            deliverables: string[];
            /** Tech Requirements */
            tech_requirements: string[];
            /** Questions */
            questions: string[];
            /** Next Action */
            next_action: string | null;
            /** Conversion Opportunity */
            conversion_opportunity: string | null;
            /** Engine */
            engine: string | null;
            /** Version */
            version: string | null;
            /** Analyzed At */
            analyzed_at: string | null;
            failure: components["schemas"]["AnalysisFailure"] | null;
        };
        /** AnalysisFailure */
        AnalysisFailure: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** AutoCollect */
        AutoCollect: {
            /** Enabled */
            enabled: boolean;
            /** Interval Minutes */
            interval_minutes: number | null;
        };
        /** BootstrapOut */
        BootstrapOut: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "demo";
            /** App Version */
            app_version: string;
            /** Api Version */
            api_version: string;
            /** Contract Version */
            contract_version: string;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Categories */
            categories: components["schemas"]["CategoryOut"][];
            /** Queues */
            queues: components["schemas"]["QueueOut"][];
            /** Recheck Ttl Hours */
            recheck_ttl_hours: number;
            /** Event Seq */
            event_seq: number;
        };
        /** Budget */
        Budget: {
            /** Used */
            used: number;
            /** Limit */
            limit: number | null;
            /** Unit Label */
            unit_label: string;
        };
        /** Capability */
        Capability: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Support
             * @enum {string}
             */
            support: "supported" | "unsupported" | "unverified";
            /** Note */
            note: string | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** CollaborationAssessed */
        CollaborationAssessed: {
            /**
             * Value
             * @enum {string}
             */
            value: "online_only" | "onsite_required" | "negotiable" | "unknown";
            /** Basis */
            basis: ("explicit" | "inferred" | "user_confirmed") | null;
        };
        /** CollectionMetrics */
        CollectionMetrics: {
            /** Period Days */
            period_days: number;
            /** Runs */
            runs: number;
            /** Requests */
            requests: number;
            /** Details Fetched */
            details_fetched: number;
            /** Created */
            created: number;
            /** Duplicates */
            duplicates: number;
            /** Parse Failures */
            parse_failures: number;
            /** Fetch Failures */
            fetch_failures: number;
            /** Policy Stops */
            policy_stops: number;
            /** Ai Failures */
            ai_failures: number;
            /**
             * Ai Cost Krw
             * @description 확인 가능한 비용 합계. 모르면 null
             */
            ai_cost_krw: number | null;
        };
        /** Coverage */
        Coverage: {
            /**
             * Target Label
             * @description 탐색 목표 (예: 전국). 실제 확인 범위와 별개
             */
            target_label: string;
            /**
             * Region List Status
             * @enum {string}
             */
            region_list_status: "verified" | "unverified" | "not_applicable" | "unknown";
            /** Unit Label */
            unit_label: string;
            /** Planned */
            planned: number | null;
            /** Completed */
            completed: number;
            /** Pending */
            pending: number;
            /** Blocked */
            blocked: number;
            /** Failed */
            failed: number;
            /** Scan Cycle */
            scan_cycle: number | null;
            /** Last Visited At */
            last_visited_at: string | null;
            /** Next Up */
            next_up: string | null;
            /** Depth Limit */
            depth_limit: number | null;
            budget: components["schemas"]["Budget"] | null;
            /**
             * Market Coverage
             * @description 원천 전체 모집단을 모르면 unknown
             * @constant
             */
            market_coverage: "unknown";
            /** Target Units Total */
            target_units_total: number | null;
            /** Target Units Covered */
            target_units_covered: number | null;
            /** Estimated Cycle Days */
            estimated_cycle_days: number | null;
            /** Notes */
            notes: string[];
        };
        /** DiscoveryPath */
        DiscoveryPath: {
            /** Region Scope */
            region_scope: string;
            /** Region Label */
            region_label: string | null;
            /** Query Group */
            query_group: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Times Seen */
            times_seen: number;
        };
        /** Draft */
        Draft: {
            /** Text */
            text: string;
            /** Generated At */
            generated_at: string | null;
            /** Edited By User */
            edited_by_user: boolean;
        };
        /** EngagementAssessed */
        EngagementAssessed: {
            /**
             * Value
             * @enum {string}
             */
            value: "project" | "hourly_contract" | "part_time" | "full_time" | "unknown";
            /** Basis */
            basis: ("explicit" | "inferred" | "user_confirmed") | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown | null;
            /** Request Id */
            request_id: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Quote */
            quote: string;
            /** @description body_text 기준 문자 위치 */
            span: components["schemas"]["Span"] | null;
            /**
             * Basis
             * @enum {string}
             */
            basis: "explicit" | "inferred" | "user_confirmed";
            /**
             * Confidence
             * @description 규칙 신뢰 수준. 모델 자기평가 확률이 아니다.
             */
            confidence: ("high" | "medium" | "low") | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Source Record Id */
            source_record_id: string;
            /** Version */
            version: string | null;
            /** Note */
            note: string | null;
        };
        /** ExportIn */
        ExportIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "leads_csv" | "leads_json" | "diagnostics";
        };
        /** FeedbackIn */
        FeedbackIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "remote" | "real_request";
            /**
             * Value
             * @enum {string}
             */
            value: "confirmed" | "denied" | "yes" | "no" | "clear";
            /** Note */
            note?: string | null;
        };
        /** FeedbackState */
        FeedbackState: {
            /** Remote */
            remote: ("confirmed" | "denied") | null;
            /** Real Request */
            real_request: ("yes" | "no") | null;
        };
        /** FuzzyDate */
        FuzzyDate: {
            /** At */
            at: string | null;
            /**
             * Precision
             * @enum {string}
             */
            precision: "exact" | "day" | "approximate" | "unknown";
            /** Raw */
            raw: string | null;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "blocked" | "error" | "paused" | "unknown";
            /** Checked At */
            checked_at: string | null;
            /** Message */
            message: string | null;
            /** Code */
            code: string | null;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "error";
            /**
             * Workers
             * @enum {string}
             */
            workers: "running" | "stopped";
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** ImportIn */
        ImportIn: {
            /**
             * Format
             * @enum {string}
             */
            format: "text" | "csv" | "json";
            /** Content */
            content: string;
            /** File Name */
            file_name?: string | null;
            /** Original Url */
            original_url?: string | null;
        };
        /** IntentAssessed */
        IntentAssessed: {
            /**
             * Value
             * @enum {string}
             */
            value: "buyer_project" | "buyer_ongoing" | "short_gig" | "employee_hiring" | "seller_service" | "job_seeker" | "information" | "unknown";
            /** Basis */
            basis: ("explicit" | "inferred" | "user_confirmed") | null;
        };
        /** JobAccepted */
        JobAccepted: {
            /** Job Id */
            job_id: string;
            /** Run Id */
            run_id: string | null;
        };
        /** LeadDetail */
        LeadDetail: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Categories */
            categories: string[];
            demand_intent: components["schemas"]["IntentAssessed"];
            engagement_type: components["schemas"]["EngagementAssessed"];
            work_mode: components["schemas"]["WorkModeAssessed"];
            collaboration_mode: components["schemas"]["CollaborationAssessed"];
            applicant_scope: components["schemas"]["ScopeAssessed"];
            pay: components["schemas"]["Pay"];
            /**
             * Source Status
             * @enum {string}
             */
            source_status: "open" | "closed" | "deleted" | "unknown";
            /**
             * Access Status
             * @enum {string}
             */
            access_status: "accessible" | "login_required" | "blocked" | "error";
            /**
             * Analysis Status
             * @enum {string}
             */
            analysis_status: "pending" | "rules_only" | "complete" | "failed" | "stale";
            /**
             * Recheck Due
             * @description 모집 중이지만 확인 TTL 이 지남
             */
            recheck_due: boolean;
            /** Last Checked At */
            last_checked_at: string | null;
            published: components["schemas"]["FuzzyDate"];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** @description 구인 마감일 (근무일·납기와 다름) */
            deadline: components["schemas"]["FuzzyDate"];
            /** Posted Region */
            posted_region: string | null;
            /**
             * Found In
             * @description 이 공고가 발견된 탐색 지역 (게시 지역과 다를 수 있음)
             */
            found_in: string[];
            /**
             * Recommendation
             * @enum {string}
             */
            recommendation: "recommended" | "needs_review" | "excluded";
            priority: components["schemas"]["Priority"];
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /** User Mark */
            user_mark: ("interested" | "dismissed") | null;
            /**
             * Sales Stage
             * @enum {string}
             */
            sales_stage: "new" | "reviewing" | "contacted" | "negotiating" | "won" | "lost" | "on_hold" | "ignored";
            /** Has Memo */
            has_memo: boolean;
            /** Active Job */
            active_job: ("recheck" | "reanalyze") | null;
            /**
             * Body Text
             * @description 안전한 텍스트. 보존 기간이 지나면 null
             */
            body_text: string | null;
            /** Body Retained Until */
            body_retained_until: string | null;
            /** Original Url */
            original_url: string | null;
            /** Contact Channel */
            contact_channel: string | null;
            /** Workplace */
            workplace: string | null;
            /** Applicant Region */
            applicant_region: string | null;
            source_updated: components["schemas"]["FuzzyDate"];
            /** Last Seen At */
            last_seen_at: string | null;
            work_period: components["schemas"]["WorkPeriod"];
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["Evidence"][];
            };
            score: components["schemas"]["ScoreBreakdown"] | null;
            analysis: components["schemas"]["Analysis"];
            /** Risks */
            risks: components["schemas"]["RiskSignal"][];
            profitability: components["schemas"]["Profitability"] | null;
            draft: components["schemas"]["Draft"] | null;
            /** Quick Message */
            quick_message: string;
            /** Memo */
            memo: string;
            /** Outcomes */
            outcomes: components["schemas"]["Outcome"][];
            /** Related */
            related: components["schemas"]["RelatedRecord"][];
            /** Discovery Paths */
            discovery_paths: components["schemas"]["DiscoveryPath"][];
            /** Activity */
            activity: components["schemas"]["Activity"][];
            feedback: components["schemas"]["FeedbackState"];
            /** Parser Version */
            parser_version: string;
            /** Content Hash */
            content_hash: string;
        };
        /** LeadPage */
        LeadPage: {
            /** Items */
            items: components["schemas"]["LeadSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Has More */
            has_more: boolean;
        };
        /** LeadPatch */
        LeadPatch: {
            /** User Mark */
            user_mark?: ("interested" | "dismissed") | null;
            /** Sales Stage */
            sales_stage?: ("new" | "reviewing" | "contacted" | "negotiating" | "won" | "lost" | "on_hold" | "ignored") | null;
            /** Memo */
            memo?: string | null;
            /** Draft Text */
            draft_text?: string | null;
        };
        /** LeadSummary */
        LeadSummary: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Categories */
            categories: string[];
            demand_intent: components["schemas"]["IntentAssessed"];
            engagement_type: components["schemas"]["EngagementAssessed"];
            work_mode: components["schemas"]["WorkModeAssessed"];
            collaboration_mode: components["schemas"]["CollaborationAssessed"];
            applicant_scope: components["schemas"]["ScopeAssessed"];
            pay: components["schemas"]["Pay"];
            /**
             * Source Status
             * @enum {string}
             */
            source_status: "open" | "closed" | "deleted" | "unknown";
            /**
             * Access Status
             * @enum {string}
             */
            access_status: "accessible" | "login_required" | "blocked" | "error";
            /**
             * Analysis Status
             * @enum {string}
             */
            analysis_status: "pending" | "rules_only" | "complete" | "failed" | "stale";
            /**
             * Recheck Due
             * @description 모집 중이지만 확인 TTL 이 지남
             */
            recheck_due: boolean;
            /** Last Checked At */
            last_checked_at: string | null;
            published: components["schemas"]["FuzzyDate"];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** @description 구인 마감일 (근무일·납기와 다름) */
            deadline: components["schemas"]["FuzzyDate"];
            /** Posted Region */
            posted_region: string | null;
            /**
             * Found In
             * @description 이 공고가 발견된 탐색 지역 (게시 지역과 다를 수 있음)
             */
            found_in: string[];
            /**
             * Recommendation
             * @enum {string}
             */
            recommendation: "recommended" | "needs_review" | "excluded";
            priority: components["schemas"]["Priority"];
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /** User Mark */
            user_mark: ("interested" | "dismissed") | null;
            /**
             * Sales Stage
             * @enum {string}
             */
            sales_stage: "new" | "reviewing" | "contacted" | "negotiating" | "won" | "lost" | "on_hold" | "ignored";
            /** Has Memo */
            has_memo: boolean;
            /** Active Job */
            active_job: ("recheck" | "reanalyze") | null;
        };
        /** MetricsOut */
        MetricsOut: {
            collection: components["schemas"]["CollectionMetrics"];
            quality: components["schemas"]["QualityMetrics"];
            sales: components["schemas"]["SalesMetrics"];
            /** Note */
            note: string;
        };
        /** NotificationSettings */
        NotificationSettings: {
            /** New Recommended */
            new_recommended: boolean;
            /** Meaningful Change */
            meaningful_change: boolean;
            /** Source Issue */
            source_issue: boolean;
            quiet_hours: components["schemas"]["QuietHours"];
        };
        /** Outcome */
        Outcome: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "contract_confirmed" | "payment_received" | "refund" | "direct_cost";
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Note */
            note: string | null;
            /** Evidence Ref */
            evidence_ref: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** OutcomeIn */
        OutcomeIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "contract_confirmed" | "payment_received" | "refund" | "direct_cost";
            /**
             * Amount
             * @description 최소 통화 단위 정수. 모르면 null
             */
            amount?: number | null;
            /**
             * Currency
             * @default KRW
             */
            currency: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Note */
            note?: string | null;
            /** Evidence Ref */
            evidence_ref?: string | null;
        };
        /** Pay */
        Pay: {
            /** Raw */
            raw: string | null;
            /** Currency */
            currency: string;
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
            /**
             * Unit
             * @enum {string}
             */
            unit: "project" | "hour" | "day" | "week" | "month" | "negotiable" | "unknown";
            /** Negotiable */
            negotiable: boolean;
        };
        /** Policy */
        Policy: {
            /**
             * Status
             * @enum {string}
             */
            status: "permission_pending" | "allowed" | "restricted" | "blocked" | "not_required";
            /** Basis */
            basis: string | null;
            /** Note */
            note: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Robots Status */
            robots_status: string;
            /** Robots Checked At */
            robots_checked_at: string | null;
            /** Robots Summary */
            robots_summary: string | null;
        };
        /** PolicyReviewIn */
        PolicyReviewIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "permission_pending" | "allowed" | "restricted" | "blocked";
            /**
             * Basis
             * @description 허용·제한 판단 근거 (약관 조항, 허가 문서 등). allowed/restricted 에 필수
             */
            basis?: string | null;
            /** Note */
            note?: string | null;
        };
        /** Priority */
        Priority: {
            /**
             * Total
             * @description 규칙 기반 우선순위 (0-100). 수주 확률이 아니다.
             */
            total: number | null;
            /** Unknown Factors */
            unknown_factors: number;
        };
        /** ProfileSettings */
        ProfileSettings: {
            /** Services */
            services: string[];
            /** Skills */
            skills: string;
            /** Excluded Work */
            excluded_work: string;
            /** Min Contract */
            min_contract: number | null;
            /** Target Hourly */
            target_hourly: number | null;
            /** Weekly Hours */
            weekly_hours: number | null;
            /**
             * Onsite
             * @enum {string}
             */
            onsite: "no" | "first_meeting" | "yes";
            /** Allow Short Term Employment */
            allow_short_term_employment: boolean;
            /**
             * Intro
             * @default
             */
            intro: string;
            /** Portfolio Url */
            portfolio_url?: string | null;
        };
        /** ProfitScenario */
        ProfitScenario: {
            /**
             * Key
             * @enum {string}
             */
            key: "conservative" | "base" | "optimistic";
            /** Contract Value */
            contract_value: number | null;
            /** Direct Cost */
            direct_cost: number | null;
            /** Hours */
            hours: number | null;
            /**
             * Contribution
             * @description 예상 기여액 = 계약 대가 - 직접 비용 (세후 순이익 아님)
             */
            contribution: number | null;
            /** Effective Hourly */
            effective_hourly: number | null;
            /** Residual After Target */
            residual_after_target: number | null;
        };
        /** Profitability */
        Profitability: {
            /**
             * Status
             * @enum {string}
             */
            status: "calculated" | "hypothesis" | "not_calculated";
            /** Basis */
            basis: string | null;
            /** Reason */
            reason: string | null;
            /** Assumptions */
            assumptions: string[];
            /** Scenarios */
            scenarios: components["schemas"]["ProfitScenario"][];
            /**
             * Revenue Type
             * @enum {string}
             */
            revenue_type: "one_time" | "recurring" | "unknown";
            /** Target Hourly */
            target_hourly: number | null;
        };
        /** Progress */
        Progress: {
            /** Done */
            done: number;
            /** Total */
            total: number | null;
            /** Label */
            label: string | null;
        };
        /** QualityMetrics */
        QualityMetrics: {
            /** Period Days */
            period_days: number;
            /**
             * Reviewed
             * @description 분모: 사용자가 판단(관심·제외·진행)을 남긴 리드 수
             */
            reviewed: number;
            /** Confirmed Fit */
            confirmed_fit: number;
            /** Remote False Positive */
            remote_false_positive: number;
            /** Buyer False Positive */
            buyer_false_positive: number;
            /** Median Hours To Review */
            median_hours_to_review: number | null;
            /** Note */
            note: string;
        };
        /** QueryGroup */
        QueryGroup: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Enabled */
            enabled: boolean;
            /** Keywords */
            keywords: string[];
        };
        /** QueryGroups */
        QueryGroups: {
            /** Version */
            version: number;
            /** Groups */
            groups: components["schemas"]["QueryGroup"][];
        };
        /** QueueCounts */
        QueueCounts: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** QueueOut */
        QueueOut: {
            /**
             * Id
             * @enum {string}
             */
            id: "recommended" | "needs_review" | "interested" | "active" | "dismissed" | "auto_excluded" | "all";
            /** Label */
            label: string;
            /** Description */
            description: string;
        };
        /** QuietHours */
        QuietHours: {
            /** Enabled */
            enabled: boolean;
            /** Start */
            start: string;
            /** End */
            end: string;
        };
        /** Reason */
        Reason: {
            /**
             * Tone
             * @enum {string}
             */
            tone: "positive" | "caution" | "negative";
            /** Text */
            text: string;
        };
        /** RelatedRecord */
        RelatedRecord: {
            /** Id */
            id: string;
            /** Lead Id */
            lead_id: string | null;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
            /**
             * Relation
             * @enum {string}
             */
            relation: "duplicate" | "repost" | "similar";
            /** Basis */
            basis: string | null;
            /**
             * Seen At
             * Format: date-time
             */
            seen_at: string;
        };
        /** Research */
        Research: {
            /** Ready */
            ready: boolean;
            /** Missing */
            missing: string[];
        };
        /** RiskPenalty */
        RiskPenalty: {
            /** Score */
            score: number;
            /** Reasons */
            reasons: string[];
        };
        /** RiskSignal */
        RiskSignal: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Quote */
            quote: string | null;
            span: components["schemas"]["Span"] | null;
        };
        /** RunActionIn */
        RunActionIn: {
            /**
             * Action
             * @enum {string}
             */
            action: "pause" | "resume" | "cancel";
        };
        /** RunCounts */
        RunCounts: {
            /** Requests */
            requests: number;
            /** Details Fetched */
            details_fetched: number;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Duplicates */
            duplicates: number;
            /** Excluded */
            excluded: number;
            /** Parse Failures */
            parse_failures: number;
            /** Fetch Failures */
            fetch_failures: number;
            /** Policy Stops */
            policy_stops: number;
            /** Ai Failures */
            ai_failures: number;
        };
        /** RunCreate */
        RunCreate: {
            /** Source Id */
            source_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "discovery" | "recheck_recent" | "recheck_stale";
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** RunError */
        RunError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retry After */
            retry_after: string | null;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string | null;
            /** Lead Id */
            lead_id: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "discovery" | "recheck_recent" | "recheck_stale" | "recheck_lead" | "reanalyze_lead" | "reanalyze_all" | "import" | "export";
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "paused" | "succeeded" | "partial" | "failed" | "cancelled";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "schedule";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            progress: components["schemas"]["Progress"];
            counts: components["schemas"]["RunCounts"];
            error: components["schemas"]["RunError"] | null;
            /** Note */
            note: string | null;
            /** Scan Cycle */
            scan_cycle: number | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["RunOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Has More */
            has_more: boolean;
        };
        /** SalesMetrics */
        SalesMetrics: {
            /** Period Days */
            period_days: number;
            /** Reviewed */
            reviewed: number;
            /** Contacted */
            contacted: number;
            /** Negotiating */
            negotiating: number;
            /** Won */
            won: number;
            /** Contracts Confirmed */
            contracts_confirmed: number;
            /** Contract Amount */
            contract_amount: number | null;
            /**
             * Collected
             * @description 실제 수금 기록 합계 (won 표시만으로 늘지 않음)
             */
            collected: number;
            /** Refunded */
            refunded: number;
            /** Direct Cost */
            direct_cost: number;
        };
        /** ScopeAssessed */
        ScopeAssessed: {
            /**
             * Value
             * @enum {string}
             */
            value: "nationwide" | "regional_restriction" | "unknown";
            /** Basis */
            basis: ("explicit" | "inferred" | "user_confirmed") | null;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /** Total */
            total: number | null;
            /** Factors */
            factors: components["schemas"]["ScoreFactor"][];
            risk_penalty: components["schemas"]["RiskPenalty"];
            /** Rule Version */
            rule_version: string;
        };
        /** ScoreFactor */
        ScoreFactor: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Max */
            max: number;
            /**
             * Score
             * @description null = 근거 부족으로 평가하지 않음 (0점과 구분)
             */
            score: number | null;
            /** Reason */
            reason: string;
        };
        /** SettingsOut */
        SettingsOut: {
            profile: components["schemas"]["ProfileSettings"];
            /** Recheck */
            recheck: {
                [key: string]: number;
            };
            notifications: components["schemas"]["NotificationSettings"];
            ai: components["schemas"]["AISettings"];
            /** Retention */
            retention: {
                [key: string]: number;
            };
            query_groups: components["schemas"]["QueryGroups"];
        };
        /** SettingsPatch */
        SettingsPatch: {
            profile?: components["schemas"]["ProfileSettings"] | null;
            /** Recheck */
            recheck?: {
                [key: string]: number;
            } | null;
            notifications?: components["schemas"]["NotificationSettings"] | null;
            /** Ai */
            ai?: {
                [key: string]: boolean | number | null;
            } | null;
            /** Retention */
            retention?: {
                [key: string]: number;
            } | null;
            /** Query Groups */
            query_groups?: components["schemas"]["QueryGroup"][] | null;
        };
        /** SourceList */
        SourceList: {
            /** Items */
            items: components["schemas"]["SourceOut"][];
        };
        /** SourceOut */
        SourceOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "site" | "manual";
            /** Scope Note */
            scope_note: string | null;
            /** Adapter Version */
            adapter_version: string;
            policy: components["schemas"]["Policy"];
            auto_collect: components["schemas"]["AutoCollect"];
            health: components["schemas"]["Health"];
            /** Stopped Reason */
            stopped_reason: string | null;
            /** Capabilities */
            capabilities: components["schemas"]["Capability"][];
            coverage: components["schemas"]["Coverage"] | null;
            research: components["schemas"]["Research"];
            /** Last Run Id */
            last_run_id: string | null;
        };
        /** SourcePatch */
        SourcePatch: {
            /** Auto Collect Enabled */
            auto_collect_enabled?: boolean | null;
            /** Interval Minutes */
            interval_minutes?: number | null;
            /**
             * Clear Stop
             * @description 차단으로 정지된 소스를 사용자가 확인 후 해제
             */
            clear_stop?: boolean | null;
            policy?: components["schemas"]["PolicyReviewIn"] | null;
        };
        /** Span */
        Span: {
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** WorkModeAssessed */
        WorkModeAssessed: {
            /**
             * Value
             * @enum {string}
             */
            value: "fully_remote" | "hybrid" | "onsite" | "negotiable" | "unknown";
            /** Basis */
            basis: ("explicit" | "inferred" | "user_confirmed") | null;
        };
        /** WorkPeriod */
        WorkPeriod: {
            start: components["schemas"]["FuzzyDate"];
            end: components["schemas"]["FuzzyDate"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bootstrap_v1_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_sources_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_source_v1_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_runs_v1_runs_get: {
        parameters: {
            query?: {
                source_id?: string | null;
                kind?: ("discovery" | "recheck_recent" | "recheck_stale" | "recheck_lead" | "reanalyze_lead" | "reanalyze_all" | "import" | "export")[] | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    run_action_v1_runs__run_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunActionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_leads_v1_leads_get: {
        parameters: {
            query?: {
                queue?: "recommended" | "needs_review" | "interested" | "active" | "dismissed" | "auto_excluded" | "all";
                limit?: number;
                cursor?: string | null;
                keyword?: string | null;
                source_id?: string | null;
                category?: string | null;
                remote?: "any" | "confirmed" | "confirmed_or_inferred" | "unknown" | "onsite";
                recruit?: "not_closed" | "open_fresh" | "recheck" | "unknown" | "closed" | "access_issue" | "any";
                intent?: "any" | "buyer" | "hiring" | "seller" | "other";
                work_mode?: ("fully_remote" | "hybrid" | "onsite" | "negotiable" | "unknown")[] | null;
                recommendation?: ("recommended" | "needs_review" | "excluded")[] | null;
                source_status?: ("open" | "closed" | "deleted" | "unknown")[] | null;
                sales_stage?: ("new" | "reviewing" | "contacted" | "negotiating" | "won" | "lost" | "on_hold" | "ignored")[] | null;
                pay_unit?: ("project" | "hour" | "day" | "week" | "month" | "negotiable" | "unknown")[] | null;
                checked_since?: string | null;
                sort?: "priority" | "published" | "checked";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    counts_v1_leads_queue_counts_get: {
        parameters: {
            query?: {
                keyword?: string | null;
                source_id?: string | null;
                category?: string | null;
                remote?: "any" | "confirmed" | "confirmed_or_inferred" | "unknown" | "onsite";
                recruit?: "not_closed" | "open_fresh" | "recheck" | "unknown" | "closed" | "access_issue" | "any";
                intent?: "any" | "buyer" | "hiring" | "seller" | "other";
                work_mode?: ("fully_remote" | "hybrid" | "onsite" | "negotiable" | "unknown")[] | null;
                recommendation?: ("recommended" | "needs_review" | "excluded")[] | null;
                source_status?: ("open" | "closed" | "deleted" | "unknown")[] | null;
                sales_stage?: ("new" | "reviewing" | "contacted" | "negotiating" | "won" | "lost" | "on_hold" | "ignored")[] | null;
                pay_unit?: ("project" | "hour" | "day" | "week" | "month" | "negotiable" | "unknown")[] | null;
                checked_since?: string | null;
                sort?: "priority" | "published" | "checked";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueCounts"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lead_detail_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_lead_v1_leads__lead_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recheck_v1_leads__lead_id__recheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reanalyze_v1_leads__lead_id__reanalyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    feedback_v1_leads__lead_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_outcome_v1_leads__lead_id__outcomes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    make_draft_v1_leads__lead_id__draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_settings_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_settings_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_import_v1_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_export_v1_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_metrics_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    events_stream_v1_events_get: {
        parameters: {
            query?: {
                after_seq?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE. Authorization 헤더 필요 (fetch 스트리밍). Last-Event-ID 또는 after_seq 로 이어받기. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
