"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 03:09:01.523708
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import worklead.db


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', worklead.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('coverage_units',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('unit_key', sa.String(length=200), nullable=False),
    sa.Column('region_scope', sa.String(length=128), nullable=False),
    sa.Column('region_label', sa.String(length=128), nullable=True),
    sa.Column('query_group', sa.String(length=64), nullable=False),
    sa.Column('last_visited_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('last_result', sa.String(length=16), nullable=True),
    sa.Column('last_scan_cycle', sa.Integer(), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source_id', 'unit_key')
    )
    op.create_table('event_outbox',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('notified_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('suppressed_reason', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('dedupe_key'),
    sa.UniqueConstraint('id')
    )
    op.create_table('host_budgets',
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('window', sa.String(length=10), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('last_request_at', worklead.db.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('host', 'window')
    )
    op.create_table('leads',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('primary_record_id', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('work_mode', sa.String(length=16), nullable=False),
    sa.Column('work_mode_basis', sa.String(length=16), nullable=True),
    sa.Column('collaboration_mode', sa.String(length=16), nullable=False),
    sa.Column('collaboration_mode_basis', sa.String(length=16), nullable=True),
    sa.Column('applicant_scope', sa.String(length=24), nullable=False),
    sa.Column('applicant_scope_basis', sa.String(length=16), nullable=True),
    sa.Column('demand_intent', sa.String(length=24), nullable=False),
    sa.Column('demand_intent_basis', sa.String(length=16), nullable=True),
    sa.Column('engagement_type', sa.String(length=24), nullable=False),
    sa.Column('engagement_type_basis', sa.String(length=16), nullable=True),
    sa.Column('recommendation', sa.String(length=16), nullable=False),
    sa.Column('priority_total', sa.Integer(), nullable=True),
    sa.Column('priority_unknown', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('analysis_status', sa.String(length=16), nullable=False),
    sa.Column('analysis_id', sa.String(length=40), nullable=True),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('access_status', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('published_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('first_seen_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('pay_unit', sa.String(length=16), nullable=False),
    sa.Column('pay_min', sa.Integer(), nullable=True),
    sa.Column('pay_max', sa.Integer(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('sales_stage', sa.String(length=16), nullable=False),
    sa.Column('user_mark', sa.String(length=16), nullable=True),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=True),
    sa.Column('draft_generated_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('draft_edited', sa.Boolean(), nullable=False),
    sa.Column('active_job', sa.String(length=16), nullable=True),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', worklead.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_checked', ['last_checked_at', 'id'], unique=False)
        batch_op.create_index('ix_leads_published', ['published_at', 'id'], unique=False)
        batch_op.create_index('ix_leads_rec_priority', ['recommendation', 'priority_total', 'id'], unique=False)
        batch_op.create_index('ix_leads_source', ['source_id'], unique=False)
        batch_op.create_index('ix_leads_stage_mark', ['sales_stage', 'user_mark'], unique=False)

    op.create_table('robots_cache',
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('host')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('adapter_version', sa.String(length=32), nullable=False),
    sa.Column('scope_note', sa.Text(), nullable=True),
    sa.Column('auto_collect_enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.String(length=16), nullable=False),
    sa.Column('health_message', sa.Text(), nullable=True),
    sa.Column('health_code', sa.String(length=64), nullable=True),
    sa.Column('health_checked_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('stopped_reason', sa.Text(), nullable=True),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', worklead.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', worklead.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=40), nullable=False),
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_krw', sa.Integer(), nullable=True),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index('ix_analysis_cache', ['cache_key'], unique=False)
        batch_op.create_index('ix_analysis_lead', ['lead_id', 'created_at'], unique=False)

    op.create_table('lead_activity',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.String(length=40), nullable=False),
    sa.Column('at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.create_index('ix_activity_lead', ['lead_id', 'at'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('occurred_on', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('evidence_ref', sa.Text(), nullable=True),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('lead_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('scan_cycle', sa.Integer(), nullable=True),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('started_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('finished_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('heartbeat_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('progress_label', sa.Text(), nullable=True),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_after', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_source_created', ['source_id', 'created_at'], unique=False)
        batch_op.create_index('ix_runs_state_created', ['state', 'created_at'], unique=False)

    op.create_table('source_policies',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=16), nullable=True),
    sa.Column('robots_status', sa.String(length=16), nullable=False),
    sa.Column('robots_checked_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('robots_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('source_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_post_id', sa.String(length=200), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('posted_region_raw', sa.Text(), nullable=True),
    sa.Column('workplace_raw', sa.Text(), nullable=True),
    sa.Column('applicant_region_raw', sa.Text(), nullable=True),
    sa.Column('published_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('published_precision', sa.String(length=16), nullable=False),
    sa.Column('published_raw', sa.Text(), nullable=True),
    sa.Column('source_updated_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('source_updated_precision', sa.String(length=16), nullable=False),
    sa.Column('source_updated_raw', sa.Text(), nullable=True),
    sa.Column('first_seen_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('last_checked_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('deadline_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('deadline_precision', sa.String(length=16), nullable=False),
    sa.Column('deadline_raw', sa.Text(), nullable=True),
    sa.Column('work_start_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('work_start_precision', sa.String(length=16), nullable=False),
    sa.Column('work_start_raw', sa.Text(), nullable=True),
    sa.Column('work_end_at', worklead.db.UTCDateTime(), nullable=True),
    sa.Column('work_end_precision', sa.String(length=16), nullable=False),
    sa.Column('work_end_raw', sa.Text(), nullable=True),
    sa.Column('pay_raw', sa.Text(), nullable=True),
    sa.Column('pay_currency', sa.String(length=8), nullable=False),
    sa.Column('pay_min', sa.Integer(), nullable=True),
    sa.Column('pay_max', sa.Integer(), nullable=True),
    sa.Column('pay_unit', sa.String(length=16), nullable=False),
    sa.Column('pay_negotiable', sa.Boolean(), nullable=False),
    sa.Column('contact_channel', sa.Text(), nullable=True),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('access_status', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('raw_retained_until', worklead.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.create_index('ix_record_lead', ['lead_id'], unique=False)
        batch_op.create_index('uq_record_canonical_url', ['source_id', 'canonical_url'], unique=True, sqlite_where=sa.text('source_post_id IS NULL AND canonical_url IS NOT NULL'))
        batch_op.create_index('uq_record_post_id', ['source_id', 'source_post_id'], unique=True, sqlite_where=sa.text('source_post_id IS NOT NULL'))

    op.create_table('user_feedback',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_tasks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('task_key', sa.String(length=400), nullable=False),
    sa.Column('query_group', sa.String(length=64), nullable=False),
    sa.Column('region_scope', sa.String(length=128), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('scan_cycle', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', worklead.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_key')
    )
    with op.batch_alter_table('collection_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_run_state', ['run_id', 'state', 'order_no'], unique=False)

    op.create_table('discovery_paths',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=40), nullable=False),
    sa.Column('region_scope', sa.String(length=128), nullable=False),
    sa.Column('query_group', sa.String(length=64), nullable=False),
    sa.Column('first_run_id', sa.String(length=40), nullable=True),
    sa.Column('first_seen_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id', 'region_scope', 'query_group')
    )
    op.create_table('duplicate_links',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=40), nullable=False),
    sa.Column('relation', sa.String(length=16), nullable=False),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'source_record_id')
    )
    op.create_table('field_evidence',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.String(length=40), nullable=False),
    sa.Column('analysis_id', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=40), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=True),
    sa.Column('observed_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_analysis', ['analysis_id'], unique=False)

    op.create_table('score_breakdowns',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.String(length=40), nullable=False),
    sa.Column('analysis_id', sa.String(length=40), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('risk_penalty', sa.JSON(), nullable=False),
    sa.Column('created_at', worklead.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=40), nullable=False),
    sa.Column('captured_at', worklead.db.UTCDateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('access_status', sa.String(length=16), nullable=False),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('retained_until', worklead.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    op.drop_table('score_breakdowns')
    with op.batch_alter_table('field_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_analysis')

    op.drop_table('field_evidence')
    op.drop_table('duplicate_links')
    op.drop_table('discovery_paths')
    with op.batch_alter_table('collection_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_run_state')

    op.drop_table('collection_tasks')
    op.drop_table('user_feedback')
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.drop_index('uq_record_post_id', sqlite_where=sa.text('source_post_id IS NOT NULL'))
        batch_op.drop_index('uq_record_canonical_url', sqlite_where=sa.text('source_post_id IS NULL AND canonical_url IS NOT NULL'))
        batch_op.drop_index('ix_record_lead')

    op.drop_table('source_records')
    op.drop_table('source_policies')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_state_created')
        batch_op.drop_index('ix_runs_source_created')

    op.drop_table('runs')
    op.drop_table('outcomes')
    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_lead')

    op.drop_table('lead_activity')
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index('ix_analysis_lead')
        batch_op.drop_index('ix_analysis_cache')

    op.drop_table('analysis_results')
    op.drop_table('user_profile')
    op.drop_table('sources')
    op.drop_table('robots_cache')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_stage_mark')
        batch_op.drop_index('ix_leads_source')
        batch_op.drop_index('ix_leads_rec_priority')
        batch_op.drop_index('ix_leads_published')
        batch_op.drop_index('ix_leads_checked')

    op.drop_table('leads')
    op.drop_table('host_budgets')
    op.drop_table('event_outbox')
    op.drop_table('coverage_units')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
